language: rust

os:
  - linux
  - osx

rust:
  # someday, but rls relies on nightly right now.
  # - stable
  # - beta
  - nightly

cache:
  - cargo

before_install:
  - nvm install 8.1.4
  - ./ci-scripts/rustfmt.sh

script:
  - rustfmt --write-mode diff build.rs
  - rustfmt --write-mode diff $(find src -type f | grep .rs)
  - rustfmt $(find tests -type f | grep .rs) || true
  - cd frontend && npm install && npm run prod && npm run test
  - cd .. && cargo build --all && cargo test --all
  - cargo run -- --manifest-path=example/Cargo.toml build
