[package]
name = "rustdoc"
version = "0.1.0"
authors = ["steveklabnik <steve@steveklabnik.com>"]
license = "MIT/Apache-2.0"

[[bin]]
name = "rustdoc"
doc = false

[lib]
# see https://github.com/steveklabnik/rustdoc/issues/22
doctest = false

[dependencies]
rls-analysis = "0.4.0"
clap = "2.24.2"
serde = "1.0.11"
serde_derive = "1.0.11"
serde_json = "1.0.2"
error-chain = "0.10.0"
indicatif = "0.6.0"
rayon = "0.8.2"

[build-dependencies]
error-chain = "0.10.0"
quote = "0.3"
syn = "0.11"
walkdir = "1.0.7"

[dev-dependencies]
error-chain = "0.10"
lazy_static = "0.2"
regex = "0.2"
shlex = "0.1"
serde_json = "1.0.2"
jsonapi = "0.5.2"
tempdir = "0.3"
